---
name: Periodic

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  markdown-link-check-periodic:
    name: Markdown Links (all files)
    if: github.repository_owner == 'submariner-io'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b

      - name: Run markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@58f84fd654812d0d8da4e4d4a559eda087daf8ce
        with:
          config-file: ".markdownlinkcheck.json"

      - name: Raise an Issue to report broken links
        if: ${{ failure() }}
        uses: peter-evans/create-issue-from-file@99b87c35610e986ad2034a7b0518a9b3ebea541b
        with:
          title: Broken link detected by CI
          content-filepath: .github/ISSUE_TEMPLATE/broken-link.md
          labels: automated, broken link
